# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Assignment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Assignment
  pod 'SnapKit', '~> 3.2.0'
  pod 'Alamofire', '~> 4.4'
  pod 'MBProgressHUD', '~> 1.0.0'
end
