# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
#inhibit_all_warnings!

target ‘TemperatureApp’ do
pod 'AFNetworking', '~> 2.5'
end
